# Generated by Django 4.1.5 on 2023-01-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('gfc', models.CharField(choices=[('2-3 Times a Week Brushing', '2-3 Times a Week Brushing'), ('Daily Brushing', 'Daily Brushing'), ('Occasional Bath/Brush', 'Occasional Bath/Brush'), ('Specialty/Professional', 'Specialty/Professional'), ('Weekly Brushing', 'Weekly Brushing')], max_length=30)),
                ('sc', models.CharField(choices=[('Frequent', 'Frequent'), ('Infrequent', 'Infrequent'), ('Occasional', 'Occasional'), ('Regularly', 'Regularly'), ('Seasonal', 'Seasonal')], max_length=30)),
                ('elc', models.CharField(choices=[('Calm', 'Calm'), ('Couch Potato', 'Couch Potato'), ('Energetic', 'Energetic'), ('Needs Lots of Activity', 'Needs Lots of Activity'), ('Regular Exercise', 'Regular Exercise')], max_length=30)),
                ('tc', models.CharField(choices=[('Agreeable', 'Agreeable'), ('Eager to Please', 'Eager to Please'), ('Easy Training', 'Easy Training'), ('Independent', 'Independent'), ('May be Stubborn', 'May be Stubborn')], max_length=30)),
                ('dc', models.CharField(choices=[('Alert/Responsive', 'Alert/Responsive'), (' Aloof/Wary', ' Aloof/Wary'), ('Friendly', 'Friendly'), ('Outgoing', 'Outgoing'), ('Reserved with Strangers', 'Reserved with Strangers')], max_length=30)),
            ],
        ),
    ]
